apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ccidp-nginx-ingress
 annotations:
   kubernetes.io/ingress.class: nginx
   nginx.ingress.kubernetes.io/affinity: "cookie"
   nginx.ingress.kubernetes.io/session-cookie-name: "route"
   nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
 tls:
 - secretName: ccidp-browser-tls
   hosts:
   - idp.mit.c3.ca
 rules:
   - host: idp.mit.c3.ca
     http:
       paths:
         - path: /
           backend:
             serviceName: ccidp-service
             servicePort: 8080
