apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shibboleth
  name: ccidp-deployment
  namespace: aai-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shibboleth
  template:
    metadata:
      labels:
        app: shibboleth
    spec:
      containers:
      - env:
        - name: JETTY_MAX_HEAP
          value: 3000m
        image: computecanada/shibboleth-idp:3.4.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /idp
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        name: idp
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /idp
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 112
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 4000Mi
        volumeMounts:
        - mountPath: /opt/shibboleth-idp/credentials
          name: credentials
        - mountPath: /opt/shibboleth-idp/ext-conf
          name: secrets
        - mountPath: /opt/shibboleth-idp/metadata
          name: shib-config
          subPath: metadata
        - mountPath: /opt/idp-conf
          name: shib-config
          subPath: conf
        - mountPath: /opt/shibboleth-idp/messages
          name: shib-config
          subPath: messages
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
            - clone
            - -b
            - 0.1.2
            - --single-branch
            - --
            - gitlab@git.computecanada.ca:cc-middleware/idp-prod-config.git
            - /shib-config
        volumeMounts:
        - name: shib-config
          mountPath: /shib-config
        - name: ssh-key
          mountPath: /root/.ssh
      volumes:
      - name: credentials
        secret:
          defaultMode: 420
          secretName: idp-keys
      - name: secrets
        secret:
          defaultMode: 420
          secretName: idp-secrets
      - name: shib-config
        emptyDir: {}
      - name: ssh-key
        secret:
          defaultMode: 0400
          secretName: gitlab-sshkey
